# Generated by Django 4.2.2 on 2023-06-21 01:57

import django.core.validators
from django.db import migrations, models
import inventario.validators


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={
                "permissions": [
                    ("reporte_cantidad", "Visualizar el reporte de cantidad"),
                    ("reporte_detalle", "Reporte detallado de cantidades"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nombre",
            field=models.CharField(
                max_length=50, validators=[inventario.validators.validation_categoria]
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(
                max_length=50,
                validators=[django.core.validators.EmailValidator("Email no valido")],
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[inventario.validators.validate_par],
            ),
        ),
    ]
